---
- hosts: dhcp
  user: vagrant
  tasks: 
    - name: crear un fichero vacia
      become: yes
      #Solo indico el plugin que voy a usar
      file: 
      #Meto todos los parametros de file
        path: /tmp/prueba_ansible
        owner: root
        group: vagrant
        mode: '0777'
        state: touch
...