---

- name: Intalar apache
  become: yes
  apt:
    name: apache2
    update_cache: yes
    state: present

- name: Levantar apache y habilitarlo en arranque
  become: yessshfs ivan@10.0.2.2:/home/ivan/Escritorio/lab/iac-center /tmp/emptyy -o IdentityFile=.vagrant/machines/ansible/virtualbox/private_key
  systemd:
    name: apache2
    state: started
    enabled: yes

- name: Creacion directorio hostvirtual zara
  become: yes
  register: zaraDirectory
  file:
    path: /var/www/zara
    state: directory
    mode: '0755'

- name: Creacion directorio hostvirtual mercadona
  become: yes
  register: mercadonaDirectory
  file:
    path: /var/www/mercadona
    state: directory
    mode: '0755'
 

- name: Creacion archivo de configuracion host virtual
  become: yes
  notify: reinicio APACHE
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - { src: zara.conf.j2, dest: /etc/apache2/sites-available/zara.conf }
    - { src: mercadona.conf.j2, dest: /etc/apache2/sites-available/mercadona.conf }
    - { src: status.conf.j2, dest: /etc/apache2/mods-available/status.conf }
    - { src: default.conf.j2, dest: /etc/apache2/sites-available/000-default.conf }

- name: Activar sitio zara
  become: yes
  register: habilitarSitioZara
  shell: "if [ -e /etc/apache2/sites-enabled/zara.conf ];then echo sitioActivadoZara;else a2ensite zara.conf;fi"

- name: Activar sitio mercadona
  become: yes
  register: habilitarSitioMercdona
  shell: "if [ -e /etc/apache2/sites-enabled/mercadona.conf ];then echo sitioActivadoMercadona;else a2ensite mercadona.conf;fi"


- name: reiniciar apache si habilito sitio zara
  become: yes
  systemd:
    name: apache2
    state: restarted
  when: '"sitioActivadoZara" not in habilitarSitioZara.stdout_lines'

- name: reiniciar apache si habilito sitio mercadona
  become: yes
  systemd:
    name: apache2
    state: restarted
  when: '"sitioActivadoMercadona" not in habilitarSitioMercdona.stdout_lines'

- name: fichero sitio zara, mercadona y apache
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{  item.dest }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - { src: "{{ zara.name }}.html", dest: "/var/www/zara/{{ zara.name }}.html "}
    - { src: "{{ mercadona.name }}.html", dest: "/var/www/mercadona/{{ mercadona.name }}.html" }
    - { src: apache2.conf, dest: /etc/apache2/apache2.conf }

- name: Activar modulos (speling)
  become: yes
  notify: reinicio APACHE
  apache2_module:
    state: present
    name: speling
...
